name: Post-Release Deploy

on:
  release:
    types:
      - published

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@v4
      - run: |
          echo "Triggered by release ${{ github.event.release.tag_name }}"
          echo "${ENV_NAME}"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
