name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: release-please-config.json
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      - run: |
          echo "release-please outputs: ${{ steps.release.outputs }}"

          echo ${{ steps.release.outputs.body }} > notes.md
          echo "${{ steps.release.outputs.tag_name }}" > release-asset.txt

          gh release create \
            ${{ steps.release.outputs.tag_name }} \
            release-asset.txt \
            --draft \
            --discussion-category "General" \
            --notes-file=notes.md
          # gh release upload ${{ steps.release.outputs.tag_name }} release-asset.txt
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        if: ${{ steps.release.outputs.release_created }}
